config:
  project_repos:
    jpl-validator:
      repo: 'https://github.com/eosc-synergy/jpl-validator'
      branch: jib-with-jpl
  credentials:
      - type: username_password
        id: orviz-dockerhub

sqa_criteria:
  qc_doc:
    repos:
      jpl-validator:
        container: gradle
        commands:
            - env
            - /jpl-validator/gradlew -p /jpl-validator jib
