config:
  credentials:
      - type: username_password
        id: orviz-dockerhub

sqa_criteria:
  qc_doc:
    repos:
      jpl-validator:
        container: gradle
        commands:
            - ls -la /jpl-validator
            - env
            - /jpl-validator/gradlew -p /jpl-validator jib
