config:
  credentials:
      - type: username_password
        id: orviz-dockerhub

sqa_criteria:
  QC.Doc:
    repos:
      jpl-validator:
        container: gradle
        commands:
            - /jpl-validator/gradlew -p /jpl-validator jib
