version: "3.6"

services:
  ajv:
    image: "3scale/ajv"
    hostname: "jpl-validator-style"
    container_name: "jpl-validator-style"
    volumes:
      - type: bind
        source: ./
        target: /jpl-validator-style
    command: sleep infinity
  gradle:
    image: "gradle"
    hostname: "jpl-validator"
    volumes:
      - type: bind
        source: ./
        target: /jpl-validator
    command: sleep infinity
